# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/alecthomas/kingpin"
  version = "2.2.3"

[[constraint]]
  name = "github.com/jkroepke/reg"
  branch = "copy-docker-image"

# https://github.com/genuinetools/reg/blob/master/Gopkg.toml

[[override]]
  name = "github.com/docker/cli"
  branch = "master"

[[override]]
  name = "github.com/docker/docker-credentials-helpers"
  branch = "master"

[[override]]
  name = "github.com/docker/go-connections"
  branch = "master"

[[override]]
  name = "github.com/prometheus/client_golang"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
